[package]
name = "webtoonSpider"
version = "0.1.0"
authors = ["George H. de Menibus <g.f.l.hellouindemenibus@student.tudelft.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
